### ISSUE TITLE
777-series heavenly upgrades config stich does not persist

### ISSUE THREAD

**Issue by sanscriptum** [staticvariablejames/SpicedCookies#2]
A config switch position for two newly added 777 heavenly upgrades is not being remembered after it has been enabled when refreshing the page.
(Also seasonal Force the Hand of Fate outcome is not explained in the readme, does it work with Fortune Cookie btw?)

**Comment by staticvariablejames** [comment]
[Fixed](https://github.com/staticvariablejames/SpicedCookies/commit/c4da06a309f8f82a1c46a765f8cde096813a1791), thanks for the bug report!

And yes, you can use the seasonal FtHoF setting with planners like Fortune Cookie; just ignore the second column. (I added this to `README.md`, thanks for the heads-up!)
